services:
  api:
    container_name: simple-integration-api
    build:
      context: ./src/SimpleIntegrationApi
      dockerfile: Dockerfile
      no_cache: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports: 
      - "8080:8080"
    networks:
      - coolify

  frontend:
    container_name: simple-integration-frontend
    build:
      context: ./src/simple-integration-app-client
      dockerfile: Dockerfile
      no_cache: true
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - coolify

  storybook:
    container_name: simple-integration-storybook
    build:
      context: ./src/simple-integration-app-client
      dockerfile: Dockerfile.storybook
      no_cache: true
    environment:
      - NODE_ENV=production
      - PORT=6006
    networks:
      - coolify

networks:
  coolify:
    external: true