services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"  # If using HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - api
      - webapp
      - storybook
    networks:
      - coolify

  api:
    container_name: simple-integration-api
    build:
      context: ./src/SimpleIntegrationApi
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
    expose:
      - "5000"
    networks:
      - coolify

  webapp:
    container_name: simple-integration-frontend
    build:
      context: ./src/simple-integration-app-client
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - API_URL=http://api:5000
    expose:
      - "3000"
    networks:
      - coolify

  storybook:
    container_name: simple-integration-storybook
    build:
      context: ./src/simple-integration-app-client
      dockerfile: Dockerfile.storybook
    expose:
      - "6006"
    networks:
      - coolify

networks:
  coolify:
    external: true