services:
  api:
    container_name: simple-integration-api
    build:
      context: ./src/SimpleIntegrationApi
      dockerfile: Dockerfile
      no_cache: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - coolify

  frontend:
    container_name: simple-integration-frontend
    build:
      context: ./src/simple-integration-app-client
      dockerfile: Dockerfile
      no_cache: true
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    networks:
      - coolify

networks:
  coolify:
    external: true