services:
  api:
    container_name: simple-integration-api-local
    build:
      context: ./src/SimpleIntegrationApi
      dockerfile: Dockerfile
      no_cache: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    container_name: simple-integration-frontend-local
    build:
      context: ./src/simple-integration-app-client
      dockerfile: Dockerfile
      no_cache: true
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - app-network

  storybook:
    container_name: simple-integration-storybook
    build:
      context: ./src/simple-integration-app-client
      dockerfile: Dockerfile.storybook
      no_cache: true
    environment:
      - NODE_ENV=production
      - PORT=6006
    ports:
      - "6006:6006"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge